export const RETRIEVE_PROJECT = 'RETRIEVE_PROJECT';
export const RETRIEVE_NEXT_PROJECTS = 'RETRIEVE_NEXT_PROJECTS';
export const GET_PROJECTS_SAMPLE = 'GET_PROJECTS_SAMPLE';
export const RETRIEVE_ALL_PROJECT_IMAGES = 'RETRIEVE_ALL_PROJECT_IMAGES';

export const NAVIGATE_TO_PROJECT = 'NAVIGATE_TO_PROJECT';
export const RETRIEVE_FULL_CASE_STUDY = 'RETRIEVE_FULL_CASE_STUDY';

export const PICK_SITE_VERSION = 'PICK_SITE_VERSION';
export const LOCK_SCROLL_X = 'LOCK_SCROLL_X';
export const CHANGE_THEME = 'CHANGE_THEME';

export const SET_FOOTER_LEFT_VISIBILITY = 'SET_FOOTER_LEFT_VISIBILITY';
export const SET_FOOTER_RIGHT_VISIBILITY = 'SET_FOOTER_RIGHT_VISIBILITY';
